import { SavedWheel } from '../types';

export const PRESET_WHEELS: SavedWheel[] = [
  {
    id: 'preset-dinner',
    title: "🍕 What's for Dinner?",
    description: "End the daily 'I don't know, you pick' dilemma once and for all!",
    category: 'food',
    themeId: 'sunset-blaze',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 5,
      spinSpeed: 'normal',
      enableSound: true,
      enableConfetti: true,
      title: "🍕 What's for Dinner?",
      centerText: 'EAT',
    },
    items: [
      { id: '1', text: 'Wood-fired Pizza', color: '#f97316', weight: 1, enabled: true, icon: '🍕', note: 'Cheesy & crispy' },
      { id: '2', text: 'Street Tacos', color: '#ef4444', weight: 1, enabled: true, icon: '🌮', note: 'With extra guac & salsa' },
      { id: '3', text: 'Fresh Sushi', color: '#ec4899', weight: 1, enabled: true, icon: '🍣', note: 'Nigiri and spicy salmon rolls' },
      { id: '4', text: 'Juicy Smash Burgers', color: '#f59e0b', weight: 1, enabled: true, icon: '🍔', note: 'With golden fries' },
      { id: '5', text: 'Thai Green Curry', color: '#10b981', weight: 1, enabled: true, icon: '🍛', note: 'Fragrant jasmine rice & coconut broth' },
      { id: '6', text: 'Homemade Pasta', color: '#8b5cf6', weight: 1, enabled: true, icon: '🍝', note: 'Creamy truffle fettuccine' },
      { id: '7', text: 'Steaming Ramen', color: '#3b82f6', weight: 1, enabled: true, icon: '🍜', note: 'Rich tonkotsu broth & soft boiled egg' },
      { id: '8', text: 'Fresh Mediterranean Bowl', color: '#06b6d4', weight: 1, enabled: true, icon: '🥗', note: 'Falafel, hummus, cucumber & feta' },
    ],
  },
  {
    id: 'preset-movie',
    title: '🎬 Movie Night Genre',
    description: 'Pick the perfect cinematic genre for tonight’s screening.',
    category: 'games',
    themeId: 'cyber-neon',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 6,
      spinSpeed: 'normal',
      enableSound: true,
      enableConfetti: true,
      title: '🎬 Movie Night Genre',
      centerText: 'FILM',
    },
    items: [
      { id: 'm1', text: 'Sci-Fi Mind Bender', color: '#06b6d4', weight: 1, enabled: true, icon: '🚀', note: 'Interstellar, Inception, Blade Runner' },
      { id: 'm2', text: '90s Nostalgia Comedy', color: '#ec4899', weight: 1, enabled: true, icon: '🍿', note: 'Clueless, Groundhog Day, Dumb & Dumber' },
      { id: 'm3', text: 'Psychological Thriller', color: '#8b5cf6', weight: 1, enabled: true, icon: '🔍', note: 'Gone Girl, Shutter Island, Zodiac' },
      { id: 'm4', text: 'Cozy Studio Ghibli / Animation', color: '#10b981', weight: 1, enabled: true, icon: '✨', note: 'Spirited Away, Spider-Verse, Ratatouille' },
      { id: 'm5', text: 'Adrenaline Action & Heist', color: '#f59e0b', weight: 1, enabled: true, icon: '💥', note: 'Mad Max, Baby Driver, Ocean\'s Eleven' },
      { id: 'm6', text: 'Mystery & Whodunnit', color: '#3b82f6', weight: 1, enabled: true, icon: '🕵️‍♂️', note: 'Knives Out, Glass Onion, Sherlock' },
      { id: 'm7', text: 'Supernatural Horror', color: '#f43f5e', weight: 1, enabled: true, icon: '👻', note: 'The Conjuring, Hereditary, Sinister' },
      { id: 'm8', text: 'Heartwarming Indie Drama', color: '#a855f7', weight: 1, enabled: true, icon: '🌻', note: 'Past Lives, Lady Bird, Little Miss Sunshine' },
    ],
  },
  {
    id: 'preset-truth-or-dare',
    title: '🎲 Truth or Dare Generator',
    description: 'Spicy, hilarious, and unforgettable party prompts!',
    category: 'party',
    themeId: 'pastel-dreams',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 4,
      spinSpeed: 'fast',
      enableSound: true,
      enableConfetti: true,
      title: '🎲 Truth or Dare',
      centerText: 'DARE',
    },
    items: [
      { id: 'td1', text: 'Truth: Most embarrassing search history', color: '#c084fc', weight: 1, enabled: true, icon: '🤫' },
      { id: 'td2', text: 'Dare: Do your best impression of someone here', color: '#f472b6', weight: 1, enabled: true, icon: '🎭' },
      { id: 'td3', text: 'Truth: Your biggest secret guilty pleasure', color: '#6ee7b7', weight: 1, enabled: true, icon: '🍫' },
      { id: 'td4', text: 'Dare: Let the group text anything to your 3rd contact', color: '#fcd34d', weight: 1, enabled: true, icon: '📱' },
      { id: 'td5', text: 'Truth: Biggest lie you ever told with a straight face', color: '#93c5fd', weight: 1, enabled: true, icon: '🤥' },
      { id: 'td6', text: 'Dare: 30-second dramatic opera singing solo', color: '#fdba74', weight: 1, enabled: true, icon: '🎶' },
      { id: 'td7', text: 'Truth: Who was your first celebrity crush?', color: '#a7f3d0', weight: 1, enabled: true, icon: '💘' },
      { id: 'td8', text: 'Dare: Do 15 pushups or balance a spoon on your nose for 20s', color: '#818cf8', weight: 1, enabled: true, icon: '🥄' },
    ],
  },
  {
    id: 'preset-icebreakers',
    title: '👥 Standup & Team Icebreaker',
    description: 'Quick, engaging questions to kickstart team meetings & standups.',
    category: 'work',
    themeId: 'ocean-depths',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 5,
      spinSpeed: 'normal',
      enableSound: true,
      enableConfetti: true,
      title: '👥 Standup Icebreaker',
      centerText: 'TEAM',
    },
    items: [
      { id: 'ib1', text: 'If you could instantly master one skill, what would it be?', color: '#0284c7', weight: 1, enabled: true, icon: '⚡' },
      { id: 'ib2', text: 'Share one underrated productivity hack or life tip', color: '#0d9488', weight: 1, enabled: true, icon: '💡' },
      { id: 'ib3', text: 'What is your favorite travel destination of all time?', color: '#2563eb', weight: 1, enabled: true, icon: '✈️' },
      { id: 'ib4', text: 'What was your dream job when you were 8 years old?', color: '#06b6d4', weight: 1, enabled: true, icon: '🚀' },
      { id: 'ib5', text: 'Current favorite podcast, book, or show you are hooked on?', color: '#1d4ed8', weight: 1, enabled: true, icon: '🎧' },
      { id: 'ib6', text: 'If you could have dinner with any historical figure, who?', color: '#14b8a6', weight: 1, enabled: true, icon: '🍽️' },
      { id: 'ib7', text: 'What is the weirdest food combo you secretly love?', color: '#3b82f6', weight: 1, enabled: true, icon: '🥑' },
      { id: 'ib8', text: 'Give a quick shoutout to someone who helped you this week!', color: '#0891b2', weight: 1, enabled: true, icon: '🌟' },
    ],
  },
  {
    id: 'preset-quick-hiit',
    title: '🏋️ Quick HIIT Workout Randomizer',
    description: 'Spin to get your next exercise burst! Keep pushing.',
    category: 'fitness',
    themeId: 'emerald-casino',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 4,
      spinSpeed: 'fast',
      enableSound: true,
      enableConfetti: true,
      title: '🏋️ Workout Bursts',
      centerText: 'GO!',
    },
    items: [
      { id: 'ex1', text: '20 Clean Pushups', color: '#059669', weight: 1, enabled: true, icon: '💪' },
      { id: 'ex2', text: '45-Second Iron Plank', color: '#d97706', weight: 1, enabled: true, icon: '⏱️' },
      { id: 'ex3', text: '15 Explosive Burpees', color: '#dc2626', weight: 1, enabled: true, icon: '🔥' },
      { id: 'ex4', text: '25 Deep Bodyweight Squats', color: '#2563eb', weight: 1, enabled: true, icon: '🦵' },
      { id: 'ex5', text: '40 Jumping Jacks', color: '#7c2d12', weight: 1, enabled: true, icon: '⚡' },
      { id: 'ex6', text: '30s Mountain Climbers', color: '#047857', weight: 1, enabled: true, icon: '🧗' },
      { id: 'ex7', text: '20 Lunges (10 each leg)', color: '#b45309', weight: 1, enabled: true, icon: '🏃' },
      { id: 'ex8', text: 'Water Break & Rest (60s)', color: '#991b1b', weight: 1, enabled: true, icon: '💧' },
    ],
  },
  {
    id: 'preset-yes-no',
    title: '🔮 The Oracle: Yes / No / Maybe',
    description: 'Instant cosmic answers to binary life dilemmas.',
    category: 'decision',
    themeId: 'midnight-luxury',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 4,
      spinSpeed: 'normal',
      enableSound: true,
      enableConfetti: true,
      title: '🔮 Oracle Wheel',
      centerText: 'FATE',
    },
    items: [
      { id: 'yn1', text: 'Definitely YES! ✨', color: '#10b981', weight: 2, enabled: true, icon: '✅' },
      { id: 'yn2', text: 'Absolutely NOT 🚫', color: '#ef4444', weight: 2, enabled: true, icon: '❌' },
      { id: 'yn3', text: 'Ask Again Later ⏳', color: '#f59e0b', weight: 1, enabled: true, icon: '🤔' },
      { id: 'yn4', text: 'Signs Point to Yes 🌟', color: '#3b82f6', weight: 1, enabled: true, icon: '👍' },
      { id: 'yn5', text: 'Don’t Count On It 🌧️', color: '#6b7280', weight: 1, enabled: true, icon: '👎' },
      { id: 'yn6', text: 'Follow Your Gut 🔥', color: '#ec4899', weight: 1, enabled: true, icon: '🎯' },
    ],
  },
  {
    id: 'preset-raffle',
    title: '🎟️ Lucky Draw & Giveaway',
    description: 'Select raffle winners fairly with elimination or multi-winner mode!',
    category: 'party',
    themeId: 'cyber-neon',
    isBuiltIn: true,
    updatedAt: Date.now(),
    config: {
      spinDuration: 6,
      spinSpeed: 'normal',
      enableSound: true,
      enableConfetti: true,
      eliminationMode: true,
      title: '🎟️ Lucky Giveaway',
      centerText: 'WIN',
    },
    items: [
      { id: 'r1', text: 'Alex Turner', color: '#06b6d4', weight: 1, enabled: true, icon: '👤' },
      { id: 'r2', text: 'Beatriz Santos', color: '#ec4899', weight: 1, enabled: true, icon: '👤' },
      { id: 'r3', text: 'Chen Wei', color: '#8b5cf6', weight: 1, enabled: true, icon: '👤' },
      { id: 'r4', text: 'Dmitri Ivanov', color: '#10b981', weight: 1, enabled: true, icon: '👤' },
      { id: 'r5', text: 'Emma Watson', color: '#f59e0b', weight: 1, enabled: true, icon: '👤' },
      { id: 'r6', text: 'Farhan Malik', color: '#3b82f6', weight: 1, enabled: true, icon: '👤' },
      { id: 'r7', text: 'Grace Hopper', color: '#f43f5e', weight: 1, enabled: true, icon: '👤' },
      { id: 'r8', text: 'Hassan Al-Sayed', color: '#a855f7', weight: 1, enabled: true, icon: '👤' },
    ],
  },
];
