import React, { useState, useEffect, useCallback, useRef, Suspense, lazy } from 'react';
import { Navbar } from './components/Navbar';
import { SliceEditor } from './components/SliceEditor';
import { AISettingsModal } from './components/AISettingsModal';
import { ExporterModal } from './components/ExporterModal';
import { Footer } from './components/Footer';
import { OnboardingTour } from './components/OnboardingTour';
import { StudioView } from './views/StudioView';
import { ErrorBoundary } from './components/ErrorBoundary';
import { TabError } from './components/TabError';
import styles from './App.module.css';

import { useLocalStorage } from './hooks/useLocalStorage';
import { SoundProvider } from './hooks/useSound.jsx';
import { useWheelEngine } from './hooks/useWheelEngine';
import { useAIConfig } from './hooks/useAIConfig';
import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts';
import { SURPRISE_PROMPTS, DEFAULT_PROMPT } from './data/constants';
import { parseVerdictPermalink } from './lib/share';
import { RefreshCw } from './lib/icons';
import { applyTheme, resolveTheme } from './lib/theme';

// Code-split heavy tab views to keep initial JS bundle ultra-fast
const CustomBuilder = lazy(() => import('./components/CustomBuilder').then(m => ({ default: m.CustomBuilder })));
const DiscoverGallery = lazy(() => import('./components/DiscoverGallery').then(m => ({ default: m.DiscoverGallery })));
const DecisionHistory = lazy(() => import('./components/DecisionHistory').then(m => ({ default: m.DecisionHistory })));
const TournamentMode = lazy(() => import('./components/TournamentMode').then(m => ({ default: m.TournamentMode })));

export function App() {
  return (
    <SoundProvider>
      <AppInner />
    </SoundProvider>
  );
}

function AppInner() {
  const [activeTab, setActiveTab] = useState('studio');
  const [isSliceEditorOpen, setIsSliceEditorOpen] = useState(false);
  const [isAISettingsOpen, setIsAISettingsOpen] = useState(false);
  const [isExporterOpen, setIsExporterOpen] = useState(false);

  const [promptInput, setPromptInput] = useState(DEFAULT_PROMPT);
  const [currentPrompt, setCurrentPrompt] = useState(DEFAULT_PROMPT);

  const [showTour, setShowTour] = useState(false);
  const [, setHasSeenTour] = useLocalStorage('spinpick_tour_seen', false);
  const [theme, setTheme] = useState(() => {
    try {
      const savedTheme = window.localStorage.getItem('spinpick_theme');
      const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      return resolveTheme(savedTheme, systemTheme);
    } catch {
      return 'dark';
    }
  });

  const { aiConfig, setAiConfig } = useAIConfig();

  useEffect(() => {
    applyTheme(theme);
  }, [theme]);

  const toggleTheme = useCallback(() => {
    setTheme((currentTheme) => (currentTheme === 'dark' ? 'light' : 'dark'));
  }, []);

  // Listen for tour start event from StudioView
  useEffect(() => {
    const handleStartTour = () => setShowTour(true);
    window.addEventListener('spinpick:start-tour', handleStartTour);
    return () => window.removeEventListener('spinpick:start-tour', handleStartTour);
  }, [setShowTour]);

  // Show onboarding tour on user action (not auto)
  // Tour is now triggered by button click in StudioView hero

  const handleDismissTour = useCallback(() => {
    setShowTour(false);
    setHasSeenTour(true);
  }, [setHasSeenTour]);

  const handleRestartTour = useCallback(() => {
    setHasSeenTour(false);
    setShowTour(true);
  }, [setHasSeenTour]);

  const isOpenRouterProxyEnabled = Boolean(import.meta.env.VITE_OPENROUTER_PROXY_URL);

  // Wheel engine handles all studio logic
  const wheelEngine = useWheelEngine({
    promptInput,
    aiConfig,
    onError: (err) => console.error('Wheel engine error:', err),
  });

  // Auto-generate the default wheel once on mount so first-time visitors land
  // on a ready-to-spin wheel (the prompt input is pre-filled with DEFAULT_PROMPT).
  // setTimeout(0) defers until the initial render commits and refs are ready.
  // No cleanup on purpose: React StrictMode double-invokes effects in dev, and a
  // clearTimeout would cancel the pending generation; the ref guard keeps it idempotent.
  // Skipped when a verdict permalink (#...) is present, so a shared verdict link
  // restores its saved options instead of being clobbered by the auto-generated wheel.
  // parseVerdictPermalink (already imported) only matches real verdict hashes, so
  // non-verdict hashes like #/studio (set by TabError recovery) still auto-generate.
  const handleGenerateRef = useRef(wheelEngine.handleGenerateOptions);
  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    if (parseVerdictPermalink(window.location.hash)) return;
    setTimeout(() => {
      handleGenerateRef.current();
    }, 0);
  }, []);

  // Keyboard shortcuts
  useKeyboardShortcuts({
    onSpin: () => wheelEngine.handleSpinComplete?.(), // Note: WheelStage handles spin internally
    onTour: () => setShowTour(true),
    setActiveTab,
    isSpinning: wheelEngine.isSpinning,
  });

  // Handle permalink hash on page load
  useEffect(() => {
    const hash = window.location.hash;
    if (hash && hash.startsWith('#')) {
      const parsed = parseVerdictPermalink(hash);
      if (parsed) {
        // Restore the verdict from permalink
        wheelEngine.setOptions(parsed.options || []);
        wheelEngine.setDisplayVerdict({
          winner: parsed.winner,
          reasoning: parsed.reasoning,
          actionSteps: parsed.actionSteps || [],
          isSensitive: false,
        });
        wheelEngine.setCurrentPrompt(parsed.prompt || '');
        wheelEngine.setPromptInput(parsed.prompt || '');
        // Clear the hash after restoring
        window.history.replaceState({}, document.title, window.location.pathname);
        // Switch to studio tab
        setActiveTab('studio');
      }
    }
  }, [wheelEngine, setActiveTab]);

  const handleSurprise = useCallback(() => {
    const picked = SURPRISE_PROMPTS[Math.floor(Math.random() * SURPRISE_PROMPTS.length)];
    setPromptInput(picked);
    wheelEngine.handleGenerateOptions(picked);
    if (activeTab !== 'studio') {
      setActiveTab('studio');
    }
  }, [activeTab, wheelEngine]);

  const handleSelectPreset = useCallback((preset) => {
    setPromptInput(preset.title);
    setCurrentPrompt(preset.title);
    wheelEngine.setOptions(preset.options);
    wheelEngine.setDisplayVerdict(null);
    wheelEngine.setTargetWinnerIndex(0);
    setActiveTab('studio');
  }, [wheelEngine]);

  const handleLoadCustomWheel = useCallback((wheelData) => {
    setPromptInput(wheelData.title);
    setCurrentPrompt(wheelData.title);
    wheelEngine.setOptions(wheelData.options);
    wheelEngine.setDisplayVerdict(null);
    wheelEngine.setTargetWinnerIndex(0);
    setActiveTab('studio');
  }, [wheelEngine]);

  const handleLoadPastSpin = useCallback((historyItem) => {
    wheelEngine.handleLoadPastSpin(historyItem);
    setActiveTab('studio');
  }, [wheelEngine]);

  return (
    <div className={`${styles.wrapper} flex-col`}>
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        openSettings={() => setIsAISettingsOpen(true)}
        onSurprise={handleSurprise}
        theme={theme}
        toggleTheme={toggleTheme}
      />

      <main id="main-content" className={`container flex-1 ${styles.mainContainer}`}>
        {/* ── STUDIO TAB ─────────────────────────────────────────── */}
        {activeTab === 'studio' && (
          <StudioView
            promptInput={promptInput}
            setPromptInput={setPromptInput}
            currentPrompt={currentPrompt}
            setCurrentPrompt={setCurrentPrompt}
            options={wheelEngine.options}
            setOptions={wheelEngine.setOptions}
            targetWinnerIndex={wheelEngine.targetWinnerIndex}
            setTargetWinnerIndex={wheelEngine.setTargetWinnerIndex}
            isSpinning={wheelEngine.isSpinning}
            setIsSpinning={wheelEngine.setIsSpinning}
            isGenerating={wheelEngine.isGenerating}
            generateError={wheelEngine.generateError}
            displayVerdict={wheelEngine.displayVerdict}
            setDisplayVerdict={wheelEngine.setDisplayVerdict}
            history={wheelEngine.history}
            setHistory={wheelEngine.setHistory}
            handleGenerateOptions={wheelEngine.handleGenerateOptions}
            handleSpinComplete={wheelEngine.handleSpinComplete}
            handleEliminateAndRespin={wheelEngine.handleEliminateAndRespin}
            handleLoadPastSpin={wheelEngine.handleLoadPastSpin}
            addHistoryItem={wheelEngine.addHistoryItem}
            onOpenSliceEditor={() => setIsSliceEditorOpen(true)}
            onOpenCriteriaTuner={() => {}}
            onOpenExporter={() => setIsExporterOpen(true)}
            onSurprise={handleSurprise}
            onSelectPreset={handleSelectPreset}
            onLoadCustomWheel={handleLoadCustomWheel}
          />
        )}

        {/* ── SECONDARY TABS WITH LAZY LOADING ───────────────────── */}
        <Suspense fallback={
          <div className={styles.suspenseFallback}>
            <RefreshCw size={24} className="spinner" />
            <p className={styles.suspenseText}>Loading studio module...</p>
          </div>
        }>
          {activeTab === 'tournament' && (
            <ErrorBoundary fallback={<TabError tab="Tournament" />}>
              <TournamentMode 
                options={wheelEngine.options} 
                onExitTournament={() => setActiveTab('studio')} 
              />
            </ErrorBoundary>
          )}

          {activeTab === 'builder' && (
            <ErrorBoundary fallback={<TabError tab="Custom Builder" />}>
              <CustomBuilder onLoadCustomWheel={handleLoadCustomWheel} />
            </ErrorBoundary>
          )}

          {activeTab === 'discover' && (
            <ErrorBoundary fallback={<TabError tab="Discover" />}>
              <DiscoverGallery onSelectPreset={handleSelectPreset} />
            </ErrorBoundary>
          )}

          {activeTab === 'history' && (
            <ErrorBoundary fallback={<TabError tab="History" />}>
              <DecisionHistory
                history={wheelEngine.history}
                onClearHistory={() => wheelEngine.setHistory([])}
                onLoadPastSpin={handleLoadPastSpin}
              />
            </ErrorBoundary>
          )}
        </Suspense>
      </main>

      <Footer hasOpenRouterProxy={isOpenRouterProxyEnabled} />

      <SliceEditor
        isOpen={isSliceEditorOpen}
        onClose={() => setIsSliceEditorOpen(false)}
        options={wheelEngine.options}
        setOptions={wheelEngine.setOptions}
      />

      <AISettingsModal
        isOpen={isAISettingsOpen}
        onClose={() => setIsAISettingsOpen(false)}
        aiConfig={aiConfig}
        setAiConfig={setAiConfig}
        onRestartTour={handleRestartTour}
      />

      <ExporterModal 
        isOpen={isExporterOpen}
        onClose={() => setIsExporterOpen(false)}
        currentPrompt={currentPrompt}
        options={wheelEngine.options}
        setOptions={wheelEngine.setOptions}
        displayVerdict={wheelEngine.displayVerdict}
      />

      <OnboardingTour
        isOpen={showTour}
        onDismiss={handleDismissTour}
      />

    </div>
  );
}